# -*- coding: utf-8 -*-
"""Career guidance chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNOSmbLZXavxIOr24svCauwB-erxedFX
"""

# CAREER GUIDANCE CHATBOT FOR UNPRIVILEGED STUDENTS
# Expanded Career Options
# Python 3

def greet_user():
    print("🤖 Hello! I am CAREER-GUIDER")
    print("I help students explore affordable and practical career options.")
    print("Let's start!\n")


def get_basic_details():
    name = input("Your name: ")
    age = input("Your age: ")
    current_class = input("Current level (Class 8-10 / Class 11-12 / Passed 12th): ")
    return name, age, current_class


def get_interests():
    print("\nSelect your main interest area:")
    print("1. Science & Technology")
    print("2. Commerce, Business & Management")
    print("3. Arts, Humanities & Media")
    print("4. Defence, Sports & Physical Services")
    print("5. Vocational, Skill-based & Self-Employment")
    print("6. Government Jobs & Competitive Exams")

    return input("Enter choice (1-6): ")


def get_financial_status():
    print("\nEducation affordability:")
    print("1. Can afford college")
    print("2. Need free / low-cost education")

    return input("Enter choice (1 or 2): ")


def suggest_careers(interest, finance):
    print("\n🎯 Career Options Suggested:\n")

    if interest == "1":  # Science & Tech
        if finance == "1":
            print("- Engineering (Computer, Civil, Mechanical, Electrical)")
            print("- Medical (MBBS, BDS, BAMS)")
            print("- B.Sc (Physics, Chemistry, Mathematics, Biotechnology)")
            print("- Data Science & AI")
            print("- Architecture")
        else:
            print("- Diploma in Engineering (Govt Polytechnic)")
            print("- ITI: Electrician, Fitter, Turner, Welder")
            print("- Lab Technician")
            print("- Radiology Technician")
            print("- Online Coding (Python, Java, Web Dev)")
            print("- Renewable Energy Technician")

    elif interest == "2":  # Commerce
        if finance == "1":
            print("- B.Com / BBA / BBM")
            print("- Chartered Accountant (CA)")
            print("- Company Secretary (CS)")
            print("- Cost & Management Accountant (CMA)")
            print("- MBA (later stage)")
        else:
            print("- Tally & GST Executive")
            print("- Banking & Insurance Exams")
            print("- Digital Marketing")
            print("- Retail Management")
            print("- E-commerce Operations")
            print("- Small Business / Startup")

    elif interest == "3":  # Arts
        print("- BA (History, Geography, Political Science, Sociology)")
        print("- Journalism & Mass Communication")
        print("- Public Administration")
        print("- Teaching (D.El.Ed / B.Ed later)")
        print("- Graphic Designing")
        print("- Content Writing & Blogging")
        print("- Animation & Video Editing")
        print("- Social Work (BSW / MSW)")

    elif interest == "4":  # Defence & Sports
        print("- Indian Army / Navy / Air Force")
        print("- NDA / CDS / AFCAT")
        print("- Paramilitary Forces (CRPF, BSF, CISF)")
        print("- Sports Coach")
        print("- Physical Education Teacher (B.P.Ed)")
        print("- Fitness Trainer")
        print("- Fire & Safety Officer")

    elif interest == "5":  # Vocational
        print("- Electrician / Plumber / Mechanic")
        print("- Mobile & Laptop Repair Technician")
        print("- Solar Panel Technician")
        print("- CCTV Installation Technician")
        print("- Tailoring & Fashion Designing")
        print("- Beautician / Salon Management")
        print("- Carpenter / Mason")
        print("- Welding & Fabrication")
        print("- Driving & Logistics Management")
        print("- Self-employed Entrepreneur")

    elif interest == "6":  # Government Jobs
        print("- SSC (CHSL, CGL, MTS)")
        print("- Banking Exams (IBPS, SBI PO/Clerk)")
        print("- Railway Jobs (RRB NTPC, Group D)")
        print("- State Government Jobs")
        print("- Police & Home Guard")
        print("- Teaching Exams (CTET, TET)")
        print("- UPSC (IAS, IPS, IFS)")
        print("- Post Office & Postal Services")
        print("- Forest Department Jobs")

    else:
        print("❌ Invalid choice")


def suggest_free_resources():
    print("\n📚 Free & Affordable Learning Resources:")
    print("- SWAYAM (Government of India)")
    print("- DIKSHA Platform")
    print("- National Skill Development Corporation (NSDC)")
    print("- PMKVY Skill Courses")
    print("- Government ITIs & Polytechnics")
    print("- YouTube Learning Channels")
    print("- National Career Service (NCS Portal)")


def closing_message(name):
    print(f"\n🌟 All the best, {name}!")
    print("Your background does NOT decide your future.")
    print("Right skills + effort can change your life.")
    print("Come back anytime 😊")


def run_chatbot():
    greet_user()
    name, age, current_class = get_basic_details()
    interest = get_interests()
    finance = get_financial_status()
    suggest_careers(interest, finance)
    suggest_free_resources()
    closing_message(name)


if __name__ == "__main__":
    run_chatbot()